### ISSUE TITLE
Lambda overhead in benchmarks.

### ISSUE THREAD

**Issue by SalomonSmeke** [dlukes/pickle-json-benchmark#2]
Hey, thanks for modernizing this gem.

I noticed a slight issue that might be worth fixing!

https://github.com/dlukes/pickle-json-benchmark/blob/2deb9089448ec22ad497c77ce37ae7b9796d9d30/test_speeds.py#L48

On my machine, the lambda costs about 100ns per fn invocation. Meaning this has a significant effect at 300000 operations (1/3rd the time).

You could fix this bias by calculating the time a lambda takes, the time a function invocation (do-nothing) takes, and subtracting them from the json times. Or invoking fewer functions by passing lists of tweets instead of tweets.

**Comment by dlukes** [comment]
Thank you for the feedback! I didn't really touch this part of the code, my intention was to keep it as similar to the original as possible while making it work under Python 3. Looking at it now, the lambda can easily be gotten rid of: https://github.com/dlukes/pickle-json-benchmark/commit/445c86d8972aa14b31603bd61b0764ae600bc465

I don't see much of a difference on my machine though, do you?

**Comment by SalomonSmeke** [comment]
To be honest I just tested calling a naked function versus calling a function wrapped in a lambda. I'm thankful that you've got the commit going!

Trying that version now, it only made a 3% difference on my machine. Which could also just be down to some thermal management stuff or who knows. I hope this was not a big/frustrating use of your time.

**Comment by dlukes** [comment]
Not at all, no worries :) I just looked at the code and realized the lambda doesn't have to be there. Which means it's just as well to get rid of it.
